@startuml

class App
class Controller
class StackFactory
class InfixTranslator

class Calculator
interface ICalculator


class StackedArrayList
class StackedVector
class StackedLinkedList
class StackedDoubleLinkedList
class StackedVector
interface Stack<E> <<interface>>
abstract class ListStack

class DoubleLinkList


App <-- Controller
Controller *-- StackFactory
Controller *-- Calculator
Controller *-- InfixTranslator

Calculator ..|> ICalculator

Stack <|.. "implements" ListStack
StackFactory *-- Stack
ListStack <-- "inherits" StackedArrayList
ListStack <-- "inherits" StackedVector
ListStack <-- "inherits" StackedLinkedList
ListStack <-- "inherits" StackedDoubleLinkedList

StackedDoubleLinkedList *-- DoubleLinkList

class App {
    + main(String[] args)
}

class StackFactory {
    + getStack() : Stack<Double>
}

class InfixTranslator{
    + InfixToPostFix(String)
}

class Controller {
    - operationFile : File
    + start()
    - fileToList(String, String): ArrayList<String>
}

class Calculator{
    - stack: Stack<Double>
    + Calculator() : Stack<Double>
    + getPrevious(): double
    + evaluate(String): double
    - operatorsAsArray(String) : String[]
}

interface ICalculator <<interface>>{
    evaluate(String): double
    getPrevious(): double
}

interface Stack {
    push(E): void
    peek(): E
    pop(): E
    empty(): boolean
    size(): int
    clear(): void
}

class ListStack{
    - data : List<E>
    + push(E): void
    + peek(): E
    + pop(): E
    + empty(): boolean
    + size(): int
    + clear(): void
}

class StackedArrayList{
    - data : ArrayList<E>
}
class StackedVector{
    - data : Vector<E>
}
class StackedLinkedList{
    - data : LinkedList<E>
}
class StackedDoubleLinkedList{
    - data : DoubleLinkList<E>
}
class DoubleLinkList <E>{
    + add(E)
    + set(E, int)
    + clear()
    + size() : int
    + get() : E
}

@enduml